apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kube-dns-autoscaler
    kubernetes.io/cluster-service: "true"
  name: kube-dns-autoscaler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-dns-autoscaler
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
      labels:
        k8s-app: kube-dns-autoscaler
    spec:
      containers:
        - name: autoscaler
          command:
            - /cluster-proportional-autoscaler
            - --configmap=kube-dns-autoscaler
            - --default-params={"linear":{"coresPerReplica":256,"nodesPerReplica":16,"min":2}}
            - --logtostderr=true
            - --mode=linear
            - --namespace=kube-system
            - --target=deployment/kube-dns
            - --v=2
          image: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0
          resources:
            requests:
              cpu: 20m
              memory: 10Mi
