# helm upgrade -i interesting-goose stable/aws-cluster-autoscaler -f helm/aws-cluster-autoscaler.yaml
---
autoscalingGroups:
  - name: kubit-workers-t2-large-a
    maxSize: 64
    minSize: 1
  - name: kubit-workers-t2-large-b
    maxSize: 64
    minSize: 1
  - name: kubit-workers-t2-large-c
    maxSize: 64
    minSize: 1

awsRegion: us-east-1

image:
  repository: gcr.io/google_containers/cluster-autoscaler
  tag: v0.4.0
  pullPolicy: IfNotPresent

extraArgs: []

podAnnotations:
  iam.amazonaws.com/role: cluster-autoscaler

replicaCount: 1

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 300Mi
  # requests:
  #   cpu: 100m
  #   memory: 300Mi

scaleDownDelay: 10m

service:
  annotations: {}
  clusterIP: ""

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  servicePort: 8085
  type: ClusterIP

skipNodes:
  withLocalStorage: false
  withSystemPods: true
