# helm install opsgoodness/kube-prometheus --namespace monitoring -f helm/kube-prometheus.yaml
---
alertmanager:
  config: {}
  externalUrl: http://alertmanager.aws.opsgoodness.net

  image:
    repository: quay.io/prometheus/alertmanager
    tag: v0.5.1

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"

    fqdn: alertmanager.aws.opsgoodness.net

    tls:
      - secretName: alertmanager.aws.opsgoodness.net
        hosts:
          - alertmanager.aws.opsgoodness.net

  nodeSelector: {}
  paused: false
  replicaCount: 3
  resources: {}

  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: 30903
    type: ClusterIP

  storageSpec:
    class: standard
    resources:
      requests:
        storage: 2Gi

prometheus:
  alertingEndpoints:
    - name: mewing-chipmunk-alertmanager
      namespace: monitoring
      port: 9093
      scheme: http

  config: {}
  externalUrl: http://prom-test.aws.opsgoodness.net

  image:
    repository: quay.io/prometheus/prometheus
    tag: v1.5.2

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"

    fqdn: prom-test.aws.opsgoodness.net

    tls:
      - secretName: prom-test.aws.opsgoodness.net
        hosts:
          - prom-test.aws.opsgoodness.net

  nodeSelector: {}
  paused: false
  replicaCount: 1
  resources: {}
  retention: 24h
  routePrefix: "/"
  rules: {}

  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: 30900
    type: ClusterIP

  serviceMonitors: []

  storageSpec:
    class: standard
    resources:
      requests:
        storage: 16Gi
