---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: standard
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
